import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import FadeTransition from "@/components/fade-transition";
// import DynamicBackground from "@/components/dynamic-background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: "black" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
        style={{ minHeight: "100vh", width: "100vw", overflowX: "hidden" }}
      >
        {/* <DynamicBackground /> */}
        <Header />
        <main className="relative min-h-screen overflow-hidden">
          <FadeTransition>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              {children}
            </div>
          </FadeTransition>
        </main>
        <Footer />
      </body>
    </html>
  );
}
